// ============================================================
// Firebase Data Connect — Database Helper Functions
// Replaces the previous Firestore helper (firestore.js)
//
// All functions use the auto-generated SDK from your schema.
// The SDK is generated by running: firebase dataconnect:sdk:generate
// Output location: src/dataconnect-sdk/
//
// GraphQL operations defined in:
//   dataconnect/connector/queries.gql
//   dataconnect/connector/mutations.gql
// ============================================================

// Import all generated query and mutation functions from the SDK
// These are auto-generated based on your schema + .gql operation files
import {
  // Doctor queries
  listApprovedDoctors,
  listDoctorsBySpecialty,
  listDoctorsByLocation,
  getDoctorById,
  listAllDoctors,
  // Slot queries
  getDoctorSlots,
  getAvailableSlots,
  // Appointment queries
  getMyAppointments,
  getDoctorAppointments,
  getTodayAppointments,
  getAllAppointments,
  getAppointmentStats,
  // User queries
  getUserByUid,
  getAllUsers,
  // Review queries
  getDoctorReviews,
  // Notification queries
  getUnreadNotifications,
  // Report queries
  getPatientReports,
  // User mutations
  createUser,
  updateUserApproval,
  // Doctor mutations
  createDoctor,
  seedDoctor,
  approveDoctorByUid,
  updateDoctorAvailability,
  updateDoctorRating,
  // Slot mutations
  addDoctorSlot,
  markSlotBooked,
  markSlotAvailable,
  deleteSlot,
  // Appointment mutations
  bookAppointment as bookAppointmentMutation,
  cancelAppointment as cancelAppointmentMutation,
  completeAppointment,
  acceptAppointment,
  rejectAppointment,
  updateAppointmentStatus,
  markAppointmentReviewed,
  // Review mutations
  submitReview as submitReviewMutation,
  // Notification mutations
  createNotification,
  markNotificationRead,
  markAllNotificationsRead,
  // Report mutations
  addMedicalReport,
  deleteMedicalReport,
} from "../dataconnect-sdk";

// ──────────────────────────────────────────────────────────────
// HELPER: Generate a unique booking ID
// ──────────────────────────────────────────────────────────────
const generateBookingId = () => "MB" + Math.floor(100000 + Math.random() * 900000);

// ──────────────────────────────────────────────────────────────
// USER OPERATIONS
// ──────────────────────────────────────────────────────────────

// Create a new user profile in PostgreSQL after Firebase Auth signup
export const createUserProfile = async ({ uid, name, email, role, phone }) => {
  const approved = role !== "doctor"; // Doctors start as unapproved
  await createUser({ uid, name, email, role, phone: phone || "", approved });
};

// Fetch a user's profile by their Firebase UID
export const getUserProfile = async (uid) => {
  try {
    const result = await getUserByUid({ uid });
    const profile = result?.data?.users?.[0] || null;
    if (profile) {
      console.log("[DataConnect] Got user profile:", profile.role);
    }
    return profile;
  } catch (err) {
    console.error("[DataConnect] Error fetching user profile:", err.message);
    return null;
  }
};

// Admin: toggle doctor/user approval
export const updateUserApprovalStatus = async (uid, approved) => {
  try {
    await updateUserApproval({ uid, approved });
  } catch (err) {
    console.error("[DataConnect] updateUserApprovalStatus error:", err.message);
    throw err;
  }
};

// Fetch all users (admin panel)
export const fetchAllUsers = async () => {
  try {
    const result = await getAllUsers();
    return result?.data?.users || [];
  } catch (err) {
    console.warn("[DataConnect] fetchAllUsers error:", err.message);
    return [];
  }
};

// Fetch all doctors (including unapproved) for admin use
export const fetchAllDoctors = async () => {
  try {
    const result = await listAllDoctors();
    return result?.data?.doctors || [];
  } catch (err) {
    console.warn("[DataConnect] fetchAllDoctors error:", err.message);
    return [];
  }
};

// Fetch a single doctor by their UID
export const fetchDoctorById = async (uid) => {
  try {
    const result = await getDoctorById({ uid });
    return result?.data?.doctors?.[0] || null;
  } catch (err) {
    console.warn("[DataConnect] fetchDoctorById error:", err.message);
    return null;
  }
};

// Fetch doctors filtered by specialty
export const fetchDoctorsBySpecialty = async (specialty) => {
  try {
    const result = await listDoctorsBySpecialty({ specialty });
    return result?.data?.doctors || [];
  } catch (err) {
    console.warn("[DataConnect] fetchDoctorsBySpecialty error:", err.message);
    return [];
  }
};

// Create a new doctor profile (called from Register page for doctor role)
export const createDoctorProfile = async (doctorData) => {
  try {
    await createDoctor({
      uid: doctorData.uid,
      name: doctorData.name,
      email: doctorData.email,
      specialty: doctorData.specialty,
      hospital: doctorData.hospital,
      location: doctorData.location,
      experience: doctorData.experience || "",
      fee: Number(doctorData.fee),
      about: doctorData.about || "",
      avatar: "👨‍⚕️",
      color: "#dbeafe",
      education: doctorData.education || "",
      languages: JSON.stringify(doctorData.languages || []),
    });
  } catch (err) {
    console.error("[DataConnect] createDoctorProfile error:", err.message);
    throw err;
  }
};

// Admin: approve or revoke a doctor
export const approveDoctorProfile = async (uid, approved) => {
  try {
    await approveDoctorByUid({ uid, approved });
    await updateUserApproval({ uid, approved });
  } catch (err) {
    console.error("[DataConnect] approveDoctorProfile error:", err.message);
    throw err;
  }
};

// Update doctor's computed average rating in DB after a new review
export const updateDoctorAverageRating = async (doctorUid, newRating, newCount) => {
  try {
    await updateDoctorRating({ uid: doctorUid, rating: newRating, reviewCount: newCount });
  } catch (err) {
    console.error("[DataConnect] updateDoctorAverageRating error:", err.message);
  }
};

// ──────────────────────────────────────────────────────────────
// DOCTOR OPERATIONS
// ──────────────────────────────────────────────────────────────

// Fetch all approved doctors for the listing page
export const fetchDoctors = async () => {
  try {
    const result = await listApprovedDoctors();
    const doctors = result?.data?.doctors || [];
    if (doctors.length > 0) {
      console.log("[DataConnect] Successfully fetched doctors from PostgreSQL:", doctors.length);
      return doctors;
    }
    console.log("[DataConnect] No approved doctors in DB, falling back to local data");
    return [];
  } catch (err) {
    console.error("[DataConnect] Error fetching doctors from PostgreSQL:", err.message);
    console.warn("[DataConnect] Falling back to local data - ensure Firebase Data Connect is set up");
    return [];
  }
};

// ──────────────────────────────────────────────────────────────
// SLOT OPERATIONS (Doctor manages their availability)
// ──────────────────────────────────────────────────────────────

// Get all available slots for a doctor across upcoming dates
export const fetchDoctorSlots = async (doctorId) => {
  try {
    const result = await getDoctorSlots({ doctorId });
    const rawSlots = result?.data?.doctorSlots || [];
    
    if (rawSlots.length > 0) {
      console.log("[DataConnect] Fetched doctor slots:", rawSlots.length);
    }
    
    // Group slots by date — returns { "2025-04-12": ["09:00 AM", "10:00 AM"], ... }
    return rawSlots.reduce((acc, slot) => {
      const dateKey = slot.date;
      if (!acc[dateKey]) acc[dateKey] = [];
      acc[dateKey].push(slot.time);
      return acc;
    }, {});
  } catch (err) {
    console.warn("[DataConnect] fetchDoctorSlots error:", err.message);
    return {};
  }
};

// Fetch available slot IDs for a specific date (needed for booking)
export const fetchAvailableSlots = async (doctorId, date) => {
  try {
    const result = await getAvailableSlots({ doctorId, date });
    return result?.data?.doctorSlots || [];
  } catch (err) {
    console.warn("[DataConnect] fetchAvailableSlots error:", err.message);
    return [];
  }
};

// Doctor adds a new availability slot
export const addSlot = async (doctorId, date, time) => {
  try {
    await addDoctorSlot({ doctorId, date, time });
  } catch (err) {
    console.error("[DataConnect] addSlot error:", err.message);
    throw err;
  }
};

// Doctor removes a slot (only unbooked ones)
export const removeSlot = async (slotId) => {
  try {
    await deleteSlot({ slotId });
  } catch (err) {
    console.error("[DataConnect] removeSlot error:", err.message);
    throw err;
  }
};

// ──────────────────────────────────────────────────────────────
// APPOINTMENT OPERATIONS
// ──────────────────────────────────────────────────────────────

// Book a new appointment:
//   1. Find and lock the slot (mark as booked)
//   2. Create the appointment record
// Note: Data Connect doesn't support transactions like Firestore,
//       so we do slot check + mark sequentially (optimistic approach)
export const bookAppointment = async ({ doctor, doctorId, date, slot, patient, patientId }) => {
  // 1. Find the slot ID for the requested date + time
  const availableSlots = await fetchAvailableSlots(doctorId, date);
  const matchedSlot = availableSlots.find((s) => s.time === slot && !s.isBooked);

  if (!matchedSlot) {
    throw new Error("This slot is no longer available. Please choose another.");
  }

  // 2. Mark the slot as booked immediately to prevent race conditions
  await markSlotBooked({ slotId: matchedSlot.id });

  try {
    // 3. Calculate token (number of appointments + 1 for that doctor on that date)
    const existing = await fetchDoctorAppointmentsData(doctorId);
    const dayAppts = existing.filter(a => a.date === date && a.status !== "Cancelled");
    const tokenNumber = dayAppts.length + 1;

    // 4. Create the appointment record in PostgreSQL
    const result = await bookAppointmentMutation({
      bookingId: generateBookingId(),
      token: tokenNumber,
      patientId,
      doctorId,
      patientName: patient.name,
      patientAge: Number(patient.age),
      patientGender: patient.gender,
      patientPhone: patient.phone,
      patientEmail: patient.email,
      doctorName: doctor.name,
      doctorSpecialty: doctor.specialty,
      doctorHospital: doctor.hospital,
      doctorFee: Number(doctor.fee),
      date,
      slot,
      reason: patient.reason,
      notes: patient.notes || "",
    });

    return result?.data?.appointment_insert;
  } catch (err) {
    // If appointment creation fails, restore the slot
    await markSlotAvailable({ slotId: matchedSlot.id });
    throw err;
  }
};

// Patient: fetch their own appointments (real-time via polling fallback)
export const fetchPatientAppointments = async (patientId) => {
  try {
    const result = await getMyAppointments({ patientId });
    const appts = result?.data?.appointments || [];
    if (appts.length > 0) {
      console.log("[DataConnect] Fetched patient appointments:", appts.length);
    }
    return appts;
  } catch (err) {
    console.warn("[DataConnect] fetchPatientAppointments error:", err.message);
    return [];
  }
};

// Doctor: fetch all their appointments
export const fetchDoctorAppointmentsData = async (doctorId) => {
  try {
    const result = await getDoctorAppointments({ doctorId });
    return result?.data?.appointments || [];
  } catch (err) {
    console.warn("[DataConnect] fetchDoctorAppointmentsData error:", err.message);
    return [];
  }
};

// Doctor: fetch only today's appointments
export const fetchTodayAppointments = async (doctorId) => {
  const today = new Date().toISOString().split("T")[0];
  try {
    const result = await getTodayAppointments({ doctorId, today });
    return result?.data?.appointments || [];
  } catch (err) {
    console.warn("[DataConnect] fetchTodayAppointments error:", err.message);
    return [];
  }
};

// Admin: fetch all appointments in the system
export const fetchAllAppointmentsData = async () => {
  try {
    const result = await getAllAppointments();
    return result?.data?.appointments || [];
  } catch (err) {
    console.warn("[DataConnect] fetchAllAppointmentsData error:", err.message);
    return [];
  }
};

// Cancel an appointment and restore the slot
export const cancelAppointmentById = async (appointmentId) => {
  try {
    await cancelAppointmentMutation({ id: appointmentId });
  } catch (err) {
    console.error("[DataConnect] cancelAppointmentById error:", err.message);
    throw err;
  }
};

// Doctor: mark appointment as completed
export const markComplete = async (appointmentId) => {
  try {
    await completeAppointment({ id: appointmentId });
  } catch (err) {
    console.error("[DataConnect] markComplete error:", err.message);
    throw err;
  }
};

// Doctor: change appointment status (generic)
export const changeAppointmentStatus = async (appointmentId, status) => {
  try {
    await updateAppointmentStatus({ id: appointmentId, status });
  } catch (err) {
    console.error("[DataConnect] changeAppointmentStatus error:", err.message);
    throw err;
  }
};

// Fetch admin analytics stats
export const fetchAppointmentStats = async () => {
  try {
    const result = await getAppointmentStats();
    const appointments = result?.data?.appointments || [];
    // Count by status in JavaScript since we can't use SQL aggregates
    const stats = {
      confirmed: appointments.filter(a => a.status === "Confirmed").length,
      completed: appointments.filter(a => a.status === "Completed").length,
      cancelled: appointments.filter(a => a.status === "Cancelled").length,
    };
    console.log("[DataConnect] Appointment stats:", stats);
    return stats;
  } catch (err) {
    console.warn("[DataConnect] fetchAppointmentStats error:", err.message);
    return { confirmed: 0, completed: 0, cancelled: 0 };
  }
};

// ──────────────────────────────────────────────────────────────
// REVIEW OPERATIONS
// ──────────────────────────────────────────────────────────────

// Submit a review and update the doctor's average rating
export const submitReview = async ({ appointmentId, patientId, doctorId, patientName, rating, comment }) => {
  try {
    // 1. Insert the review row
    await submitReviewMutation({ appointmentId, patientId, doctorId, patientName, rating, comment });

    // 2. Mark the appointment as reviewed
    await markAppointmentReviewed({ id: appointmentId });

    // 3. Recalculate doctor's average rating from all reviews
    const allReviews = await getDoctorReviews({ doctorId });
    const reviews = allReviews?.data?.reviews || [];
    if (reviews.length > 0) {
      const avg = reviews.reduce((sum, r) => sum + r.rating, 0) / reviews.length;
      await updateDoctorAverageRating(doctorId, Math.round(avg * 10) / 10, reviews.length);
    }
  } catch (err) {
    console.error("[DataConnect] submitReview error:", err.message);
    throw err;
  }
};

// Fetch all reviews for a doctor profile page
export const fetchDoctorReviews = async (doctorId) => {
  try {
    const result = await getDoctorReviews({ doctorId });
    return result?.data?.reviews || [];
  } catch (err) {
    console.warn("[DataConnect] fetchDoctorReviews error:", err.message);
    return [];
  }
};

// ──────────────────────────────────────────────────────────────
// NOTIFICATION OPERATIONS
// ──────────────────────────────────────────────────────────────

// Send a notification to a specific user
export const sendNotification = async (userId, message, type = "info") => {
  try {
    await createNotification({ userId, message, type });
  } catch (err) {
    console.warn("[DataConnect] sendNotification error:", err.message);
  }
};

// Fetch unread notifications for the notification bell
export const fetchNotifications = async (userId) => {
  try {
    const result = await getUnreadNotifications({ userId });
    return result?.data?.notifications || [];
  } catch (err) {
    console.warn("[DataConnect] fetchNotifications error:", err.message);
    return [];
  }
};

// Mark a single notification as read
export const dismissNotification = async (notificationId) => {
  try {
    await markNotificationRead({ id: notificationId });
  } catch (err) {
    console.warn("[DataConnect] dismissNotification error:", err.message);
  }
};

// Mark all notifications as read for a user
export const dismissAllNotifications = async (userId) => {
  try {
    await markAllNotificationsRead({ userId });
  } catch (err) {
    console.warn("[DataConnect] dismissAllNotifications error:", err.message);
  }
};

// ──────────────────────────────────────────────────────────────
// REPORT OPERATIONS
// ──────────────────────────────────────────────────────────────

// Fetch all medical reports for a patient
export const fetchPatientReports = async (patientId) => {
  try {
    const result = await getPatientReports({ patientId });
    return result?.data?.medicalReports || [];
  } catch (err) {
    console.warn("[DataConnect] fetchPatientReports error:", err.message);
    return [];
  }
};

// Save medical report metadata after Cloudinary upload
export const addReport = async (reportData) => {
  try {
    const result = await addMedicalReport(reportData);
    return result?.data?.medicalReport_insert;
  } catch (err) {
    console.error("[DataConnect] addReport error:", err.message);
    throw err;
  }
};

// Remove a medical report from the vault
export const deleteReport = async (reportId) => {
  try {
    await deleteMedicalReport({ id: reportId });
  } catch (err) {
    console.error("[DataConnect] deleteReport error:", err.message);
    throw err;
  }
};
